const BOARD_WIDTH = 480;
const BOARD_HEIGHT = 480;
const HALF_WIDTH = BOARD_WIDTH / 2;
const GRID = 20;
const COLUMNS = 24;
const BOUNDARIES = [0, BOARD_WIDTH - GRID];
const SNAKE_LENGTH = 4;
const SNAKE_COLOR = '#268bd2';
const LEFT = 'LEFT';
const RIGHT = 'RIGHT';
const DOWN = 'DOWN';
const UP = 'UP';

const RAVENCLAW = 'RAVENCLAW';
const GRYFFINDOR = 'GRYFFINDOR';
const SLYTHERIN = 'SLYTHERIN';
const HUFFLEPUFF = 'HUFFLEPUFF';

const HOUSES = {
  RAVENCLAW: '#071A80',
  GRYFFINDOR: '#941B08',
  SLYTHERIN: '#154C07',
  HUFFLEPUFF: '#F1F31C',
};